@extends('layout.member')
@section('leave')
<table class="table table-striped">
    <thead>
    <th>S.N.</th>
    <th>English Date</th>
    <th>Nepali Date</th>
    <th>Day</th>
    <th>Holiday</th>
    </thead>
    <tbody>
    <tr>
        <td>Kusum Gole</td>
        <td>Quality Assurance</td>
        <td>8am</td>
        <td>5pm</td>
        <td>Online</td>
    </tr>
    <tr>
        <td>Kusum2</td>
        <td>Developer</td>
        <td>9am</td>
        <td>7pm</td>
        <td>Offline</td>
    </tr>
    <tr>
        <td>Kusum2</td>
        <td>Developer</td>
        <td>9am</td>
        <td>7pm</td>
        <td>Offline</td>
    </tr><tr>
        <td>Kusum2</td>
        <td>Developer</td>
        <td>9am</td>
        <td>7pm</td>
        <td>Offline</td>
    </tr><tr>
        <td>Kusum2</td>
        <td>Developer</td>
        <td>9am</td>
        <td>7pm</td>
        <td>Offline</td>
    </tr><tr>
        <td>Kusum2</td>
        <td>Developer</td>
        <td>9am</td>
        <td>7pm</td>
        <td>Offline</td>
    </tr><tr>
        <td>Kusum2</td>
        <td>Developer</td>
        <td>9am</td>
        <td>7pm</td>
        <td>Offline</td>
    </tr><tr>
        <td>Kusum2</td>
        <td>Developer</td>
        <td>9am</td>
        <td>7pm</td>
        <td>Offline</td>
    </tr><tr>
        <td>Kusum2</td>
        <td>Developer</td>
        <td>9am</td>
        <td>7pm</td>
        <td>Offline</td>
    </tr><tr>
        <td>Kusum2</td>
        <td>Developer</td>
        <td>9am</td>
        <td>7pm</td>
        <td>Offline</td>
    </tr>
    </tbody>
</table>
    @stop